### ISSUE TITLE
`Resource` interface doesn't account for `['*']`

### ISSUE THREAD

**Issue by shellscape** [m-elbably/simple-access#2]
Hey there. Thanks for this package, well done.

I noticed that the docs mention use of:

```
```

But the typing here https://github.com/m-elbably/simple-access/blob/593e5f8714f142b7df760a138275259e80960cc1/src/types/common.ts#L19-L22 doesn't allow for that. 

It should be declared as:

```ts
// https://stackoverflow.com/questions/41139763/how-to-declare-a-fixed-length-array-in-typescript
type ArrayLengthMutationKeys = 'splice' | 'push' | 'pop' | 'shift' | 'unshift' | number
type ArrayItems<T extends Array<any>> = T extends Array<infer TItems> ? TItems : never
type FixedLengthArray<T extends any[]> =
  Pick<T, Exclude<keyof T, ArrayLengthMutationKeys>>
  & { [Symbol.iterator]: () => IterableIterator< ArrayItems<T> > }
  
export interface Resource {
    name: string;
    actions: FixedLengthArray<['*']> | Array<Action>;
}
```

**Comment by shellscape** [comment]
```
export interface Action {
    name: string;
    attributes?: Array<string>;
    conditions?: Array<string>;
    scope?: {
        [k: string]: Tuple;
    };
}
```

Also seems to be incorrect as the example roles schema from the README does not pass type checks.

**Comment by m-elbably** [comment]
@shellscape You're right, I forgot to add the type `Role[]` to the `Roles` array in the test data which prevented the TS compiler help as it's considered as `any`, I will update the types, and the test data.

**Comment by shellscape** [comment]
Thanks very much.

For what it's worth, I made a fork today to resolve the type errors, and you can see their resolution on this commit https://github.com/shellscape/simple-access/commit/73118f18d28a0d9610003c30cd6c2d5069f83f4b. There is quite a bit more there that I did to bring the project up to date with the projects I maintain, so hopefully that is useful. If you would like to use the changes in my fork as well, you are welcome to do so. I would also be happy to open a pull request for those changes.

**Comment by m-elbably** [comment]
> ```
> export interface Action {
>     name: string;
>     attributes?: Array<string>;
>     conditions?: Array<string>;
>     scope?: {
>         [k: string]: Tuple;
>     };
> }
> ```
> 
> Also seems to be incorrect as the example roles schema from the README does not pass type checks.

Yes, `conditions` should be an array of objects.
Actually, I'm considering removing `sift` and `conditions` as it has a lot of side effects, in complex applications I use `scope` to define any custom attributes and evaluate them within the application logic which is more secure.

**Comment by shellscape** [comment]
> Actually, I'm considering removing sift and conditions as it has a lot of side effects, in complex applications I use scope to define any custom attributes and evaluate them within the application logic which is more secure.

@m-elbably How do you use `scope` and `filter` to compare a resource object with a subject object? We were using those conditions quite heavily. For example:

```
"conditions": [
  {
    "subject.team_id": {
      "$eq": "resource.owner"
    }
  }
],
```

**Comment by m-elbably** [comment]
> > Actually, I'm considering removing sift and conditions as it has a lot of side effects, in complex applications I use scope to define any custom attributes and evaluate them within the application logic which is more secure.
> 
> @m-elbably How do you use `scope` and `filter` to compare a resource object with a subject object? We were using those conditions quite heavily. For example:
> 
> ```
> "conditions": [
>   {
>     "subject.team_id": {
>       "$eq": "resource.owner"
>     }
>   }
> ],
> ```

For example, if we have `admin` and `customer` roles, user only has access to its own profile, admin may access all profiles but only specific attributes, so `admin` access to `profile` resource may look like:
```json
{
  "name": "profiles",
  "actions": [
     { "name": "read", "attributes": ["*", "!password"] }
   ]
}
```
And `customer` resource may look like this
```json
{
  "name": "profiles",
  "actions": [
     { "name": "read", "attributes": ["*", "!password"], "scope": {"own": true}}
   ]
}
```

Then when you use `can` function to check access, the returned `permission` will include the ` scope` object.<br>

With application logic, you can check the returned permission if `scope.own` is true then you can do a comparison between the subject id and the appropriate resource attribute, if not then it means that the user has higher privilege and can access profiles.

finally use `filter` function by passing the `permission` and the `resource` and it will omit `password` attribute as mentioned in role schema.

Its more secure and fixable to do it like this.

**Comment by shellscape** [comment]
I see what you're saying, but that's not what I'm asking. We originally chose the package because it gave us the ability to specify conditional relationships between a resource and a subject, _and_ define that up front in a schema rather than code. `scope` doesn't provide the same mechanism. I'm not sure what "secure" means in this context, but removing that part of functionality removes a large part of attribute based access control is all about. It's cool if you weren't comfortable with that part of the code/feature in the package, but it's crucial to our needs, and I wanted to share that. Unless there's a good way to add that back in, we'll have to go with a fork off of the 1.x version.

**Comment by m-elbably** [comment]
> I see what you're saying, but that's not what I'm asking. We originally chose the package because it gave us the ability to specify conditional relationships between a resource and a subject, _and_ define that up front in a schema rather than code. `scope` doesn't provide the same mechanism. I'm not sure what "secure" means in this context, but removing that part of functionality removes a large part of attribute based access control is all about. It's cool if you weren't comfortable with that part of the code/feature in the package, but it's crucial to our needs, and I wanted to share that. Unless there's a good way to add that back in, we'll have to go with a fork off of the 1.x version.

Sure you can use v1.x as long as you need to go with the declarative approach, I'm looking into a another way to get it back, the current approach depends on resolving `key` and `query` of conditions may lead to inconsistency in some cases like comparing the `key` for example `subject.id` which is numeric and resolved as string value to another numeric value, also when `key` and/or  `query` is `null` or undefined.
